"""Changed promotion date to datetime

Revision ID: 010d6599ba7d
Revises: c5cf82f556a5
Create Date: 2025-06-05 16:59:34.444329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010d6599ba7d'
down_revision: Union[str, None] = 'c5cf82f556a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('promotions', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'end_time')
    op.drop_column('promotions', 'start_time')
    # ### end Alembic commands ###
