"""Add CafeTable and relation to Order

Revision ID: c5cf82f556a5
Revises: f63f4a4b53dc
Create Date: 2025-06-04 23:56:01.157656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cf82f556a5'
down_revision: Union[str, None] = 'f63f4a4b53dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'cafe_tables', ['table_id'], ['id'])
    op.drop_column('orders', 'table_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'table_id')
    op.drop_table('cafe_tables')
    # ### end Alembic commands ###
